name: Release Artifacts
on:
  push:
    tags:
      - 'v*'
jobs:
  wheel-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.4.1'
      - name: Install release dependencies
        run: pip install -U twine wheel typer mistletoe
      - name: Build packages
        run: |
          poetry build
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/qiskit*
      - name: Extract changelog
        run: python scripts/extract-changelog.py ${{ github.ref_name }} | tee ${{ github.workspace }}-CHANGELOG.txt
      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/qiskit*
          body_path: ${{ github.workspace }}-CHANGELOG.txt
      - name: Publish to AQT package registry
        env:
          TWINE_PASSWORD: ${{ secrets.AQT_PACKAGE_REGISTRY_WRITE_TOKEN }}
          TWINE_USERNAME: github-pypi-python-packages-upload
        run: twine upload --repository-url ${{ secrets.AQT_PACKAGE_REGISTRY_URL }} dist/qiskit*
      - name: Publish to AQT-partners package registry
        env:
          TWINE_PASSWORD: ${{ secrets.AQT_PARTNERS_PACKAGE_REGISTRY_WRITE_TOKEN }}
          TWINE_USERNAME: github-pypi-python-packages-upload
        run: twine upload --repository-url ${{ secrets.AQT_PARTNERS_PACKAGE_REGISTRY_URL }} dist/qiskit*
